### PR TITLE
fix #322: scale bandscope for any number of samples

### LINKED ISSUE #322: Spectrum marker doesn't fit to frequency
After the successfull bugfix of the spectrum with V3.7 it looks, like in some situation the frequency marker does not fit the detected and displayed maximum frequency.

grafik
Sample 1: 405.700 MHz is the maximun in the right half of the display, marker is in the left.

grafik
Sample 2: 405.300 MHz has been detected, marker should be near to the center, where the maximum bar is correct displayed

I noticed this on all my radios with FW3.7 and a friend of mine confirmed the same error on his radios. 

It looks, like the marker is being calculated depending on the old (smaller) buggy range in some cases. Sometimes the marker is being displayed with a delay of > 5 Sec. at the correct position.

You might have to change resolution/decimation and frequency range to reproduce this behaviour.

### PR DESCRIPTION
**Pull request by jflinchbaugh**
retain stretch of bars for short ranges, but after 128 samples, scale 1:1 to always fill the width of the screen.

PXL_20250108_043043423
PXL_20250108_041908509
PXL_20250108_042147948

### CODE REVIEW

File: app/spectrum.c [hunk 1]
```diff
@@ -870,13 +870,16 @@ uint8_t Rssi2Y(uint16_t rssi)
 #ifdef ENABLE_FEAT_F4HWN_SPECTRUM
     static void DrawSpectrum()
     {
+        uint16_t steps = GetStepsCount();
+        uint16_t scale = (steps > 128) ? 128 : steps;
+        uint16_t shift = 64 / steps + 1;
```
Comment (jflinchbaugh) [inline app/spectrum.c:875]: i don't know which is more valuable: calculation time or storage. maybe these could be inlined to save space, but I think the render may be faster avoiding the recalculation.

File: app/spectrum.c [hunk 2]
```diff
@@ -870,13 +870,16 @@ uint8_t Rssi2Y(uint16_t rssi)
 #ifdef ENABLE_FEAT_F4HWN_SPECTRUM
     static void DrawSpectrum()
     {
+        uint16_t steps = GetStepsCount();
+        uint16_t bars = (steps > 128) ? 128 : steps;
+        uint16_t shift_graph = 64 / steps + 1; // to center bar on freq marker
```
Comment (jflinchbaugh) [inline app/spectrum.c:875]: i don't know which is more valuable: calculation time or storage. maybe these could be inlined to save space, but I think the render may be faster avoiding the recalculation.

**Comment by armel** [comment]
Merge on [feature_update_v4](https://github.com/armel/uv-k5-firmware-custom/tree/feature_update_v4). 
Will be fixed in next release. 
Good job @jflinchbaugh and thank a lot for this contribution.
